import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Terms and conditions for using ReviewMint, the automated Google review management platform.",
};

export default function TermsPage() {
  return (
    <article className="prose-legal">
      <h1>Terms of Service</h1>
      <p className="lead">
        Last updated: September 4, 2026
      </p>

      <p>
        These Terms of Service (&quot;Terms&quot;) govern your use of{" "}
        <strong>ReviewMint</strong>, operated by{" "}
        <strong>NovaMint Networks</strong>. By creating an account or using the
        Service, you agree to these Terms.
      </p>

      <h2>1. Eligibility</h2>
      <p>
        You must be at least 18 years old and authorized to enter into these
        Terms on behalf of yourself or the business you represent. You must
        have a valid Google Business Profile to use the review management
        features.
      </p>

      <h2>2. Account Responsibilities</h2>
      <ul>
        <li>
          You are responsible for maintaining the security of your account
          credentials.
        </li>
        <li>
          You are responsible for all activity that occurs under your account.
        </li>
        <li>
          You must provide accurate business information when configuring review
          reply settings.
        </li>
        <li>
          You must not share your account with unauthorized individuals.
        </li>
      </ul>

      <h2>3. The Service</h2>
      <p>ReviewMint provides:</p>
      <ul>
        <li>
          <strong>Automated Review Replies</strong> — AI-generated replies
          posted to your Google Business Profile reviews in your configured
          voice and tone.
        </li>
        <li>
          <strong>Review Request Campaigns</strong> — Ability to send review
          request messages to your customers via WhatsApp and email.
        </li>
        <li>
          <strong>Review Analytics</strong> — Dashboard showing review trends,
          ratings, and response metrics.
        </li>
      </ul>

      <h2>4. Credits & Wallet</h2>
      <ul>
        <li>
          WhatsApp messages require credits, which can be purchased via the
          Wallet page using Cashfree Payments.
        </li>
        <li>
          Credit prices are dynamic and may change based on Meta&apos;s
          WhatsApp Business API pricing.
        </li>
        <li>
          Credits are non-transferable between accounts.
        </li>
        <li>
          Unused credits do not expire as long as your account remains active.
        </li>
        <li>
          Consumed credits (messages sent) are non-refundable.
        </li>
      </ul>

      <h2>5. WhatsApp Messaging Compliance</h2>
      <p>When using WhatsApp review requests, you agree to:</p>
      <ul>
        <li>
          Only message customers who have a genuine business relationship with
          you and have consented to receive communications.
        </li>
        <li>
          Not use the Service for spam, harassment, or unsolicited marketing.
        </li>
        <li>
          Comply with Meta&apos;s{" "}
          <a
            href="https://www.whatsapp.com/legal/business-policy"
            target="_blank"
            rel="noopener noreferrer"
          >
            WhatsApp Business Policy
          </a>{" "}
          and{" "}
          <a
            href="https://www.whatsapp.com/legal/commerce-policy"
            target="_blank"
            rel="noopener noreferrer"
          >
            Commerce Policy
          </a>
          .
        </li>
        <li>
          Comply with India&apos;s{" "}
          <strong>
            Digital Personal Data Protection Act (DPDPA), 2023
          </strong>{" "}
          regarding customer consent and data handling.
        </li>
      </ul>

      <h2>6. Acceptable Use</h2>
      <p>You must not:</p>
      <ul>
        <li>Use the Service for any illegal or fraudulent purpose</li>
        <li>Post fake reviews or manipulate review ratings</li>
        <li>
          Attempt to reverse engineer, decompile, or exploit the Service
        </li>
        <li>
          Use automated scripts or bots to interact with the Service beyond
          what is provided
        </li>
        <li>
          Exceed rate limits or attempt to overwhelm our infrastructure
        </li>
      </ul>

      <h2>7. AI-Generated Content</h2>
      <p>
        Review replies are generated by AI based on your configured tone and
        business context. While we strive for accuracy and appropriateness:
      </p>
      <ul>
        <li>
          You are ultimately responsible for all replies posted to your Google
          Business Profile.
        </li>
        <li>
          We recommend reviewing AI-generated replies regularly, especially
          during the initial setup period.
        </li>
        <li>
          We are not liable for any business impact resulting from AI-generated
          replies.
        </li>
      </ul>

      <h2>8. Intellectual Property</h2>
      <p>
        ReviewMint&apos;s brand, code, design, and AI models are the
        intellectual property of NovaMint Networks. Your business data remains
        yours — we claim no ownership over your reviews, customer lists, or
        business information.
      </p>

      <h2>9. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, NovaMint Networks shall not be
        liable for:
      </p>
      <ul>
        <li>
          Indirect, incidental, special, or consequential damages
        </li>
        <li>
          Loss of revenue or business due to Service downtime or AI reply
          quality
        </li>
        <li>
          Actions taken by third-party services (Google, Meta, Cashfree)
        </li>
        <li>
          Data loss resulting from your failure to maintain account security
        </li>
      </ul>
      <p>
        Our total liability shall not exceed the amount you paid to us in the
        12 months preceding the claim.
      </p>

      <h2>10. Termination</h2>
      <ul>
        <li>
          You may terminate your account at any time from the Settings page.
        </li>
        <li>
          We may suspend or terminate your account for violations of these
          Terms, with notice where possible.
        </li>
        <li>
          Upon termination, your data will be deleted within 30 days.
          Previously posted Google review replies will remain on Google.
        </li>
      </ul>

      <h2>11. Governing Law</h2>
      <p>
        These Terms are governed by the laws of India. Any disputes shall be
        subject to the exclusive jurisdiction of courts in Rajasthan, India.
      </p>

      <h2>12. Changes</h2>
      <p>
        We may modify these Terms at any time. Material changes will be
        communicated via email. Continued use after changes constitutes
        acceptance.
      </p>

      <h2>13. Contact</h2>
      <p>
        For questions about these Terms:
      </p>
      <ul>
        <li>
          <strong>Email</strong>:{" "}
          <a href="mailto:support.novamintnetworks@gmail.com">
            support.novamintnetworks@gmail.com
          </a>
        </li>
        <li>
          <strong>Company</strong>: NovaMint Networks
        </li>
      </ul>
    </article>
  );
}
